// Seznam držav s klicnimi številkami (E.164 klicne kode) - za izbiro
// države pri vnosu telefonske številke na javnem obrazcu (naročnikova
// zahteva 7.9.2026, po zgledu priloženega zaslonskega posnetka). Zastavice
// prikazuje "flag-icons" paket (SVG, glej src/components/IzbiraDrzave.tsx)
// - NE Unicode emoji, ker jih Windows privzeto ne izriše kot slike, ampak
// pokaže samo dve črki kode države (dejansko opaženo pri testiranju).
export interface Drzava {
  id: string; // ISO 3166-1 alpha-2
  naziv: string;
  klicnaStevilka: string; // z "+" predpono
  // [min, max] število števk telefonske številke BREZ klicne kode - privzeto
  // [6, 12], natančneje nastavljeno za SI/HR (edini dve državi, v katerih
  // podjetje trenutno posluje, glej Lokacija.drzava).
  dolzinaStevilke?: [number, number];
}

export const PRIVZETA_DOLZINA_STEVILKE: [number, number] = [6, 12];

export const DRZAVE: Drzava[] = [
  { id: "SI", naziv: "Slovenija", klicnaStevilka: "+386", dolzinaStevilke: [8, 8] },
  { id: "HR", naziv: "Hrvaška", klicnaStevilka: "+385", dolzinaStevilke: [8, 9] },
  { id: "AT", naziv: "Avstrija", klicnaStevilka: "+43" },
  { id: "IT", naziv: "Italija", klicnaStevilka: "+39" },
  { id: "DE", naziv: "Nemčija", klicnaStevilka: "+49" },
  { id: "HU", naziv: "Madžarska", klicnaStevilka: "+36" },
  { id: "CH", naziv: "Švica", klicnaStevilka: "+41" },
  { id: "FR", naziv: "Francija", klicnaStevilka: "+33" },
  { id: "ES", naziv: "Španija", klicnaStevilka: "+34" },
  { id: "PT", naziv: "Portugalska", klicnaStevilka: "+351" },
  { id: "GB", naziv: "Združeno kraljestvo", klicnaStevilka: "+44" },
  { id: "IE", naziv: "Irska", klicnaStevilka: "+353" },
  { id: "NL", naziv: "Nizozemska", klicnaStevilka: "+31" },
  { id: "BE", naziv: "Belgija", klicnaStevilka: "+32" },
  { id: "LU", naziv: "Luksemburg", klicnaStevilka: "+352" },
  { id: "DK", naziv: "Danska", klicnaStevilka: "+45" },
  { id: "SE", naziv: "Švedska", klicnaStevilka: "+46" },
  { id: "NO", naziv: "Norveška", klicnaStevilka: "+47" },
  { id: "FI", naziv: "Finska", klicnaStevilka: "+358" },
  { id: "IS", naziv: "Islandija", klicnaStevilka: "+354" },
  { id: "PL", naziv: "Poljska", klicnaStevilka: "+48" },
  { id: "CZ", naziv: "Češka", klicnaStevilka: "+420" },
  { id: "SK", naziv: "Slovaška", klicnaStevilka: "+421" },
  { id: "RO", naziv: "Romunija", klicnaStevilka: "+40" },
  { id: "BG", naziv: "Bolgarija", klicnaStevilka: "+359" },
  { id: "GR", naziv: "Grčija", klicnaStevilka: "+30" },
  { id: "CY", naziv: "Ciper", klicnaStevilka: "+357" },
  { id: "MT", naziv: "Malta", klicnaStevilka: "+356" },
  { id: "EE", naziv: "Estonija", klicnaStevilka: "+372" },
  { id: "LV", naziv: "Latvija", klicnaStevilka: "+371" },
  { id: "LT", naziv: "Litva", klicnaStevilka: "+370" },
  { id: "BA", naziv: "Bosna in Hercegovina", klicnaStevilka: "+387" },
  { id: "RS", naziv: "Srbija", klicnaStevilka: "+381" },
  { id: "ME", naziv: "Črna gora", klicnaStevilka: "+382" },
  { id: "MK", naziv: "Severna Makedonija", klicnaStevilka: "+389" },
  { id: "AL", naziv: "Albanija", klicnaStevilka: "+355" },
  { id: "XK", naziv: "Kosovo", klicnaStevilka: "+383" },
  { id: "UA", naziv: "Ukrajina", klicnaStevilka: "+380" },
  { id: "MD", naziv: "Moldavija", klicnaStevilka: "+373" },
  { id: "BY", naziv: "Belorusija", klicnaStevilka: "+375" },
  { id: "RU", naziv: "Rusija", klicnaStevilka: "+7" },
  { id: "TR", naziv: "Turčija", klicnaStevilka: "+90" },
  { id: "LI", naziv: "Lihtenštajn", klicnaStevilka: "+423" },
  { id: "MC", naziv: "Monako", klicnaStevilka: "+377" },
  { id: "SM", naziv: "San Marino", klicnaStevilka: "+378" },
  { id: "VA", naziv: "Vatikan", klicnaStevilka: "+379" },
  { id: "AD", naziv: "Andora", klicnaStevilka: "+376" },
  // Amerika
  { id: "US", naziv: "ZDA", klicnaStevilka: "+1" },
  { id: "CA", naziv: "Kanada", klicnaStevilka: "+1" },
  { id: "MX", naziv: "Mehika", klicnaStevilka: "+52" },
  { id: "BR", naziv: "Brazilija", klicnaStevilka: "+55" },
  { id: "AR", naziv: "Argentina", klicnaStevilka: "+54" },
  { id: "CL", naziv: "Čile", klicnaStevilka: "+56" },
  { id: "CO", naziv: "Kolumbija", klicnaStevilka: "+57" },
  { id: "PE", naziv: "Peru", klicnaStevilka: "+51" },
  { id: "VE", naziv: "Venezuela", klicnaStevilka: "+58" },
  { id: "EC", naziv: "Ekvador", klicnaStevilka: "+593" },
  { id: "BO", naziv: "Bolivija", klicnaStevilka: "+591" },
  { id: "PY", naziv: "Paragvaj", klicnaStevilka: "+595" },
  { id: "UY", naziv: "Urugvaj", klicnaStevilka: "+598" },
  { id: "CR", naziv: "Kostarika", klicnaStevilka: "+506" },
  { id: "PA", naziv: "Panama", klicnaStevilka: "+507" },
  { id: "CU", naziv: "Kuba", klicnaStevilka: "+53" },
  { id: "DO", naziv: "Dominikanska republika", klicnaStevilka: "+1" },
  { id: "GT", naziv: "Gvatemala", klicnaStevilka: "+502" },
  { id: "HN", naziv: "Honduras", klicnaStevilka: "+504" },
  { id: "SV", naziv: "Salvador", klicnaStevilka: "+503" },
  { id: "NI", naziv: "Nikaragva", klicnaStevilka: "+505" },
  { id: "JM", naziv: "Jamajka", klicnaStevilka: "+1" },
  // Azija
  { id: "CN", naziv: "Kitajska", klicnaStevilka: "+86" },
  { id: "JP", naziv: "Japonska", klicnaStevilka: "+81" },
  { id: "KR", naziv: "Južna Koreja", klicnaStevilka: "+82" },
  { id: "IN", naziv: "Indija", klicnaStevilka: "+91" },
  { id: "PK", naziv: "Pakistan", klicnaStevilka: "+92" },
  { id: "BD", naziv: "Bangladeš", klicnaStevilka: "+880" },
  { id: "ID", naziv: "Indonezija", klicnaStevilka: "+62" },
  { id: "MY", naziv: "Malezija", klicnaStevilka: "+60" },
  { id: "SG", naziv: "Singapur", klicnaStevilka: "+65" },
  { id: "TH", naziv: "Tajska", klicnaStevilka: "+66" },
  { id: "VN", naziv: "Vietnam", klicnaStevilka: "+84" },
  { id: "PH", naziv: "Filipini", klicnaStevilka: "+63" },
  { id: "TW", naziv: "Tajvan", klicnaStevilka: "+886" },
  { id: "HK", naziv: "Hongkong", klicnaStevilka: "+852" },
  { id: "IL", naziv: "Izrael", klicnaStevilka: "+972" },
  { id: "SA", naziv: "Savdska Arabija", klicnaStevilka: "+966" },
  { id: "AE", naziv: "Združeni arabski emirati", klicnaStevilka: "+971" },
  { id: "QA", naziv: "Katar", klicnaStevilka: "+974" },
  { id: "KW", naziv: "Kuvajt", klicnaStevilka: "+965" },
  { id: "BH", naziv: "Bahrajn", klicnaStevilka: "+973" },
  { id: "OM", naziv: "Oman", klicnaStevilka: "+968" },
  { id: "JO", naziv: "Jordanija", klicnaStevilka: "+962" },
  { id: "LB", naziv: "Libanon", klicnaStevilka: "+961" },
  { id: "IQ", naziv: "Irak", klicnaStevilka: "+964" },
  { id: "IR", naziv: "Iran", klicnaStevilka: "+98" },
  { id: "AF", naziv: "Afganistan", klicnaStevilka: "+93" },
  { id: "KZ", naziv: "Kazahstan", klicnaStevilka: "+7" },
  { id: "UZ", naziv: "Uzbekistan", klicnaStevilka: "+998" },
  { id: "GE", naziv: "Gruzija", klicnaStevilka: "+995" },
  { id: "AM", naziv: "Armenija", klicnaStevilka: "+374" },
  { id: "AZ", naziv: "Azerbajdžan", klicnaStevilka: "+994" },
  { id: "NP", naziv: "Nepal", klicnaStevilka: "+977" },
  { id: "LK", naziv: "Šrilanka", klicnaStevilka: "+94" },
  { id: "MM", naziv: "Mjanmar", klicnaStevilka: "+95" },
  { id: "KH", naziv: "Kambodža", klicnaStevilka: "+855" },
  { id: "LA", naziv: "Laos", klicnaStevilka: "+856" },
  // Afrika
  { id: "EG", naziv: "Egipt", klicnaStevilka: "+20" },
  { id: "ZA", naziv: "Južnoafriška republika", klicnaStevilka: "+27" },
  { id: "NG", naziv: "Nigerija", klicnaStevilka: "+234" },
  { id: "KE", naziv: "Kenija", klicnaStevilka: "+254" },
  { id: "MA", naziv: "Maroko", klicnaStevilka: "+212" },
  { id: "DZ", naziv: "Alžirija", klicnaStevilka: "+213" },
  { id: "TN", naziv: "Tunizija", klicnaStevilka: "+216" },
  { id: "LY", naziv: "Libija", klicnaStevilka: "+218" },
  { id: "ET", naziv: "Etiopija", klicnaStevilka: "+251" },
  { id: "GH", naziv: "Gana", klicnaStevilka: "+233" },
  { id: "TZ", naziv: "Tanzanija", klicnaStevilka: "+255" },
  { id: "UG", naziv: "Uganda", klicnaStevilka: "+256" },
  { id: "SN", naziv: "Senegal", klicnaStevilka: "+221" },
  { id: "CI", naziv: "Slonokoščena obala", klicnaStevilka: "+225" },
  { id: "CM", naziv: "Kamerun", klicnaStevilka: "+237" },
  { id: "ZM", naziv: "Zambija", klicnaStevilka: "+260" },
  { id: "ZW", naziv: "Zimbabve", klicnaStevilka: "+263" },
  { id: "MZ", naziv: "Mozambik", klicnaStevilka: "+258" },
  { id: "AO", naziv: "Angola", klicnaStevilka: "+244" },
  { id: "NA", naziv: "Namibija", klicnaStevilka: "+264" },
  { id: "BW", naziv: "Bocvana", klicnaStevilka: "+267" },
  // Oceanija
  { id: "AU", naziv: "Avstralija", klicnaStevilka: "+61" },
  { id: "NZ", naziv: "Nova Zelandija", klicnaStevilka: "+64" },
  { id: "FJ", naziv: "Fidži", klicnaStevilka: "+679" },
];

export function najdiDrzavo(id: string): Drzava {
  return DRZAVE.find((d) => d.id === id) ?? DRZAVE[0];
}
